### ISSUE TITLE
About the algorithm flow

### ISSUE THREAD

**Issue by qhykwsw** [mks0601/V2V-PoseNet_RELEASE#11]
Thank you for your research. I read your code line by line and I have two questions as follows:
(1) Firstly, I was confused about why you first voxelize the whole image, then discretize the extracted hand, instead of the opposite. This will not increase the amount of calculation?
(2) Secondly, in the function named "scattering()", why the lower_mask and the upper_mask are set to choose coords between 1 to 88 instead of -44 to 43. 
Thanks again for your patience.

**Comment by mks0601** [comment]
(1) If you crop the hand in 2D depth image and voxelize it, the perspective distortion (visualized in our paper) still exists in voxelized one. We compared the performance of 1) voxelized the image and crop the hand in 3D space (free from perspective distortion) vs 2) crop the hand in 2D depth map and voxelize it (not free from perspective distortion) and realized that 1) results in better accuracy.

(2) The discretize function outputs coordinates from 0 to croppedSz.

**Comment by qhykwsw** [comment]
Thank you for your quick reply. On the second question, the reference point you set is in the position of the center of mass. If the discretize function outputs coordinates from 0 to croppedSz, should the cropped area be a part of the whole hand?

**Comment by mks0601** [comment]
In the generate_cubic_input function, the discretize function (line 105) takes coordinates which is normalized from -1 to 1 and discretize them from 0 to croppedSz-1 (if the normalized coordinate is 1, then it outputs croppedSz, however not that big issue). 

After data augmentation from line 108 to 131, line 134 round the coordinate and shift the coordinate from 1 to croppedSz.

Does this explanation help your understanding?

**Comment by qhykwsw** [comment]
Oh, I finally understand, Thank you so much for your explanation. At the beginning, I also didn't know why "coord[1] = (coord[1] - refPt[1])/(cubicSz/2)" does the normalization. Because not all the coordinates of the points are regularized from -1 to 1. It turned out that it only focused on the points in the cube without having to manage points outside the cube.

**Comment by mks0601** [comment]
That`s right. Ask me anything if you have any question in the future. I will close this issue.
