### ISSUE TITLE
Lua files not found

### ISSUE THREAD

**Issue by ghost** [mks0601/V2V-PoseNet_RELEASE#12]
Hi there,

First of all, thank you for providing this code and for replying to previous issues.
For a graduation project, I try to get this repository running. I installed all dependencies and cloned the repository. I think there is a minor typo in README.md, so run from my `src` directory:
`th run_me.lua`
This results in an error:
`/usr/bin/luajit: /usr/share/lua/5.1/trepl/init.lua:389: module 'cunn' not found:`
`	no field package.preload['cunn']`
`	no file './cunn.lua'`
`	no file '/usr/share/luajit-2.1.0-beta3/cunn.lua'`
`	no file '/usr/local/share/lua/5.1/cunn.lua'`
`	no file '/usr/local/share/lua/5.1/cunn/init.lua'`
`	no file '/usr/share/lua/5.1/cunn.lua'`
`	no file '/usr/share/lua/5.1/cunn/init.lua'`
`	no file './cunn.so'`
`	no file '/usr/local/lib/lua/5.1/cunn.so'`
`	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/cunn.so'`
`	no file '/usr/local/lib/lua/5.1/loadall.so'`
`stack traceback:`
`	[C]: in function 'error'`
`	/usr/share/lua/5.1/trepl/init.lua:389: in function 'require'`
`	run_me.lua:2: in main chunk`
`	[C]: in function 'dofile'`
`	/usr/lib/torch-trepl/th:149: in main chunk`
`	[C]: at 0x559c7c0dc1d0`

Lua is installed, however: `$ luajit` works just fine. What am I missing?

**Comment by mks0601** [comment]
You need to install several cuda related modules such as cutorch and cunn.
Try 
luarocks install cutorch
luarocks install cunn
