### ISSUE TITLE
no visible label 'INVALIDFRAME_TRAIN'

### ISSUE THREAD

**Issue by rsluo** [mks0601/V2V-PoseNet_RELEASE#14]
Thanks for sharing your code! When I try to run "th run_me.lua" I get an error message:

./data/ICVL/data.lua:234: no visible label 'INVALIDFRAME_TRAIN' for <goto> at line 163
stack traceback:
	[C]: in function 'dofile'
	run_me.lua:18: in main chunk
	[C]: in function 'dofile'
	...sluo/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: in ?

Do you know what the issue could be? Thanks!

**Comment by mks0601** [comment]
Sorry, there were few typos in ICVL/data.lua
I commited a new version!

**Comment by rsluo** [comment]
Thanks!
