### ISSUE TITLE
Pre-computed centers

### ISSUE THREAD

**Issue by rsluo** [mks0601/V2V-PoseNet_RELEASE#15]
I want to run V2V for hand pose estimation on some RGBD data that I have, but I don't have any ground truth labels. What exactly is the format of the center_trainset and center_testset text files, and how did you get that information? Thanks!

**Comment by mks0601** [comment]
It is mentioned in the README.MD.

The precomputed centers are obtained by training the hand center estimation network from DeepPrior++ . Each line represents 3D world coordinate of each frame. In case of ICVL, NYU, MSRA dataset, if depth map is not exist or not contain hand, that frame is considered as invalid. In case of ITOP dataset, if 'valid' variable of a certain frame is false, that frame is considered as invalid. All test images are considered as valid.

**Comment by rsluo** [comment]
Thanks! I guess I missed that earlier. 

One more question - do you have code for visualizing the results?

**Comment by mks0601** [comment]
Sorry for late reply. I used plot and plot3 function in MATLAB. The visualization code wil be uploaded soon.

**Comment by rsluo** [comment]
Ok, thanks!

**Comment by mks0601** [comment]
I have just uploaded visualization code. You can check the code and instruction in the README.MD

**Comment by rsluo** [comment]
Thank you!
