### ISSUE TITLE
how to use the pre-trained models ?

### ISSUE THREAD

**Issue by Dzhange** [mks0601/V2V-PoseNet_RELEASE#16]
could you please give me some instructions?

**Comment by mks0601** [comment]
You can download the pretrained model in the README file and set resume = true to resume the training from the pretrained model. The directory you should place the pretrained model file is in the data/*/data.lua

**Comment by Dzhange** [comment]
THANK YOU VERY MUCH !!! (by the way, I'm really looking forward to your visualization code!)

**Comment by mks0601** [comment]
I have just uploaded visualization code. You can check the code and instruction in the README.MD
