### ISSUE TITLE
Generate cubic input and data augmentation

### ISSUE THREAD

**Issue by PengfeiRen96** [mks0601/V2V-PoseNet_RELEASE#17]
I have two questions as follows:
(1) Firstly, I know the corpped img size is 96(pixel) in DeepPrior++ and REN,but i was confused about why you set oringinalSz =96 in generate_cubic_input()?And why you use "originalSz" and "croppedSz" variables.
(2) Secondly, in generate_cubic_input(), why you use the following code to resize the data instead of multiplying a coefficient directly？
 if newSz < 100 then
        coord = coord / originalSz * math.floor(originalSz*newSz/100) + math.floor(originalSz/2 - originalSz/2*newSz/100)
    elseif newSz > 100 then
        coord = coord / originalSz * math.floor(originalSz*newSz/100) - math.floor(originalSz/2*newSz/100 - originalSz/2)
end

**Comment by mks0601** [comment]
(1) I don`t know the cropped img size in DeepPrior++ and REN is 96, but that is not related with my setting. The reason why I defined originalSz and croppedSz is for translation data augmentation.

(2) what do you mean by multiplying a coefficient? which coefficient do you mean?

**Comment by PengfeiRen96** [comment]
Thank you for your reply.
(1)Now i understand the originalSz and croppedSz is defined for translation data augmentation. And i wonder to know does the translation is [-4, 4] voxels in your code:
    local trans = torch.Tensor(worldDim)
    trans[1] = torch.random(1,originalSz-croppedSz+1)
    trans[2] = torch.random(1,originalSz-croppedSz+1)
    trans[3] = torch.random(1,originalSz-croppedSz+1)
    --discretize
    coord = discretize(coord)
    coord = coord + (originalSz/2 - croppedSz/2)
    --translation
    coord[1] = coord[1] - (trans[1] - 1)
    coord[2] = coord[2] - (trans[2] - 1)
    coord[3] = coord[3] - (trans[3] - 1)
(2)I mistaked for the meaning of “newSz”.I used to think is stand for voxel.

**Comment by mks0601** [comment]
Sorry for late reply. 
(1) No. The translation is [-8. 8] as described in the paper.
