### ISSUE TITLE
The MSRA dataset is incomplete

### ISSUE THREAD

**Issue by fanglinpu** [mks0601/V2V-PoseNet_RELEASE#18]
Thank you for sharing nice research work.
I find that the  MSRA dataset from the provided link is incomplete, where did you get the complete dataset?

**Comment by mks0601** [comment]
Is it incomplete? Maybe you can contact with Xiao Sun through email. I cannot remember exactly how I get the MSRA dataset.

**Comment by fanglinpu** [comment]
Thank you anyway, I have solve this problem.
