### ISSUE TITLE
Training with custom dataset

### ISSUE THREAD

**Issue by konrad-marzec** [mks0601/V2V-PoseNet_RELEASE#21]
Hi, I have created my own custom dataset. I have disparity maps and want to finetune V2V-posenet.  Can you explain what the following values are ? How you get them from presented datasets ?
```
fx = 241.42
fy = 241.42
cubicSz = 200

minDepth = 100
maxDepth = 700
```

**Comment by mks0601** [comment]
Hi.

fx, fy are focal length of the camera in mm.
cubicSz is the length of one edge of a cubic to crop a hand in the 3D space.
minDepth and maxDepth are some kind of heuristic parameter to localize the center-of-mass of the hand.

**Comment by konrad-marzec** [comment]
thanks :)
