### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by jayala** [mks0601/V2V-PoseNet_RELEASE#23]
Hello,
we are trying to test the pre-trained models but the link is not working, can you give us a hand?

[https://image.ibb.co/mnGFvf/Captura-de-pantalla-de-2018-10-16-08-53-21.png](https://image.ibb.co/mnGFvf/Captura-de-pantalla-de-2018-10-16-08-53-21.png)

**Comment by mks0601** [comment]
Hi. Recently, http link of our university is not working well. I modified the README file to contain https links instead of http ones. It should work now.

**Comment by jayala** [comment]
Thanks a lot!
