### ISSUE TITLE
ITOP dataset

### ISSUE THREAD

**Issue by bhavesh-red-d** [mks0601/V2V-PoseNet_RELEASE#24]
any chance i could get the ITOP dataset?? The link provided is down.
thanks

**Comment by mks0601** [comment]
I downloaded it to my disk, however I wonder kind of copyright issue can be a problem if I distribute it. I think you have to contact to the authors of ITOP dataset.

**Comment by bhavesh-red-d** [comment]
I did try to contact Albert(Author).. haven't gotten any response.. now the site seems to be down.. so i was trying to source it from other sources.. can you plz check the license file if it allows distribution(if the data-set has a license file). The the dataset would be a great help.

**Comment by bhavesh-red-d** [comment]
Got the dataset..

**Comment by HuntleyZ** [comment]
> Got the dataset..

Could you pls share the dataset? Both the download link or the Google Drive link is Ok. I've also contacted the authors and haven't got any response too...

**Comment by HuntleyZ** [comment]
@freAkiee 

Hello, could you pls share the dataset? Both the download link or the Google Drive link is Ok. I've also contacted the authors and haven't got any response too...

**Comment by HuntleyZ** [comment]
For those who haven't found the dataset...
The dataset is available on the website: www.albert.cm/projects/viewpoint_3d_pose/

**Comment by saileshprem** [comment]
It's now available at: https://www.alberthaque.com/projects/viewpoint_3d_pose/

**Comment by mks0601** [comment]
Thanks. I'll update my README

**Comment by ahaque** [comment]
Sorry for changing the link. As of July 2020, the ITOP dataset has moved to a permanent dataset hosting website, with it's own DOI: https://zenodo.org/record/3932973

The old link still works but now redirects to Zenodo.
