### ISSUE TITLE
Testing with Pre-trained Model and Data

### ISSUE THREAD

**Issue by diealecel** [mks0601/V2V-PoseNet_RELEASE#25]
Hi, I've been trying to test the pre-trained ICVL model (from GitHub) with the ICVL data (linked from GitHub) and keep running into this error.

```
Found Environment variable CUDNN_PATH = /usr/local/cuda-8.0/lib64/libcudnn.so.5db: ICVL mode: test	
model loading...	
testing data loading...	
invalid frame in test set: 0	
==> testing:
/home/diego/research/torch/install/bin/luajit: invalid arguments: FloatTensor nil 
expected arguments: [*FloatTensor*] FloatTensor FloatTensor
stack traceback:
	[C]: at 0x7fb7dd940bd0
	[C]: in function 'cmul'
	./data/ICVL/data.lua:46: in function 'pixel2world'
	util.lua:96: in function 'generate_cubic_input'
	test.lua:42: in function 'test'
	run_me.lua:78: in main chunk
	[C]: in function 'dofile'
	...arch/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
```

Any ideas what is going on? I haven't changed anything other than where the model, centers, and data are located.

**Comment by mks0601** [comment]
The error comes from util.lua: 96th line.
I think you should check you correctly load the depthimage.

**Comment by diealecel** [comment]
Thank you for such a prompt reply!

Ah, I realized that my .bin files weren't ready yet. I've fixed that and can now get results for the testing sets. However, I've noticed that I still receive this error after the dataset has been parsed through. Thus, I thought there might be some number in the codebase that expects more .bin files than there actually are.

I wondered if the testSz value in src/data/ICVL/data.lua had to do with it. In the ICVL testing set there are 702 entries. However, entering this number didn't change anything—it actually made it such that I could get no results. Do you know what could be causing this?

**Comment by drt040312** [comment]
Hi ！
I CAN NOT GET the dataset "ITOP Human Pose Dataset [link] [paper]",because I can't link to the "link" URL. Do I have any other path to get this data set?

**Comment by LETMEY** [comment]
@drt040312 Hi!
Have you got this dataset, please?

**Comment by mks0601** [comment]
I updated link in README
