### ISSUE TITLE
The Details of ITOP points.

### ISSUE THREAD

**Issue by SLIiii** [mks0601/V2V-PoseNet_RELEASE#26]
Hi,In the line 54 of "test.lua",for ITOP dataset,the model output a Tensor named "xyzOutput" which  have 15 rows.
Unfortunately,The web of ITOP has been closed. 
I'm wondering that corresponding to the human part,what these rows exactly represent?
For example,maybe row 1 represent 'Head'.

**Comment by SLIiii** [comment]
The Other question is what the unit of  "xyzOutput"? 
Is the "mAP" means the propotion of Euclidean distance between "xyzOutput" and "real_joint" which less than 0.1m?

**Comment by mks0601** [comment]
1. The description of each body part is in data/ITOP/data.lua
2. I think the xyzOutput is the real-world coordinates of each joint in meter. The mAP means what you asked which is described in my paper.

**Comment by SLIiii** [comment]
Thanks for your response and I have found the definition of mAP in section 8.2 of your paper.
But I can't find the the labels of each body part in data/ITOP/data.lua. Can you give some more details?

**Comment by mks0601** [comment]
--head(1), neck(2), r_shoulder(3), l_shoulder(4), r_elbow(5), l_elbow(6), r_hand(7), l_hand(8)
--torso(9), r_hip(10), l_hip(11), r_knee(12), l_knee(13), r_foot(14), l_foot(15)

You can find them in src/data/ITOP/data.lua

**Comment by SLIiii** [comment]
Thanks,I find it in the line 3 of 'data.lua' under your reminding. It turns out to be Note and I didn't notice before.= =、

**Comment by mks0601** [comment]
Alright. Ask me anything if you encounter another problem :)
