### ISSUE TITLE
error in data.lua of MSRA dataset

### ISSUE THREAD

**Issue by dragonbook** [mks0601/V2V-PoseNet_RELEASE#29]
in src/data/MSRA/data.lua, line 136,137: "jointWorld = torch.Tensor(trainSz,jointNum,worldDim):zero() ...", I guess it should change the trainSz if it is in 'test' mode?

**Comment by mks0601** [comment]
Oh, you're right. It should be 'testSz'. I'll fix it. Thanks for pointing out.
