### ISSUE TITLE
Experimental Comparison

### ISSUE THREAD

**Issue by xinghuokang** [mks0601/V2V-PoseNet_RELEASE#3]
Hi, Gyeongsik,
My research is human pose estimate. Is it convenient to share your training code or pre-trained model for human pose estimating?

**Comment by mks0601** [comment]
Hi, xinghuokang
Do you want to train model with my code? Or just want to compare the result with your method?

**Comment by xinghuokang** [comment]
Hi, thank you for your reply quickly. I have read many articles of "hand pose estimate", and most of them say "It is also fit for 'Human pose Estimate'", I just want to seen the result of my own data sets.  So, train code or trained model for human pose estimate , its belongs to you. In practice, I am also interested in 3D conv-net used in your article, and converting input depth map to voxels.

**Comment by mks0601** [comment]
I updated source code to include human pose estimation training and testing.
Actually, most of the code is the same except for the data loading part.

You can download the pre-computed center and estimated result of my code in README.MD.

**Comment by xinghuokang** [comment]
Thank you!

**Comment by mks0601** [comment]
Close the issue. Feel free to ask me if you meet any problems.

**Comment by xinghuokang** [comment]
Thank you very much!

2018-03-29 10:47 GMT+08:00 Gyeongsik Moon <notifications@github.com>:
