### ISSUE TITLE
A PyTorch implementation

### ISSUE THREAD

**Issue by dragonbook** [mks0601/V2V-PoseNet_RELEASE#32]
Hi,
I have recently implemented your excellent work with PyTorch(https://github.com/dragonbook/V2V-PoseNet-pytorch).  After some tests, it should work well now. I think it may be some useful for other pytorch users, so I posted it here. You can optionally add this to REAME :)

Thanks.

**Comment by mks0601** [comment]
Hi dragonbook,

Thank you for re-implementing my work on PyTorch. I tried to re-implement it to recent deep learning frameworks such as PyTorch or TensorFlow, however, I was so busy :( I will add your repo on my README.
