### ISSUE TITLE
Change output heatmap's resolution up to 88x88x88

### ISSUE THREAD

**Issue by dragonbook** [mks0601/V2V-PoseNet_RELEASE#33]
Hi,
I want to change the network's output  resolution up to 88x88x88(that is, double the current heatmap's size) to simply enlarge estimation precision. Since your current network is pretty good now, I chose to simply adjust it by inserting one more decoder(with a upsample layer) block after original encoder-decoder block to double it's output(which is 44x44x44). (I also tried to add a longer skip/residual connection at original scale(88x88x88)). But they seems not to work much well like your original one in my experiments(emm..., actually some of them do work).

I wonder how do you designed your current network, except the common practices, like residual block and U-net like skip-connection. E.g. you used U-net style in a encoder-decoder sub-block in middle of the architecture after one basic conv layer, one pool layer and some residual blocks. What's your considerations? 

Besides, Did you consider feature map cell's receptive field(in order to catch larger 3d context) when you design network? Did you try some experiments/network designs on 88x88x88 output resolution? Could you talk some experience or give me some suggestions?

Thanks!

**Comment by mks0601** [comment]
Hi dragonbook,

I experimented your case and it does not improve the performance much, while consuming computational cost much more. When I designed my model, I considered receptive field size and conventional U-Net structure stuffs. 

I think you have to set sigma value used to generate gt heatmap larger than the original one. Otherwise, it would generate too small blob on the gt heatmap (because of enlarged output heatmap size), so the model would have a difficulty to learning to localize hand keypoints.

**Comment by dragonbook** [comment]
Thanks for your advice!

Yes, I doubled sigma(1.7 up to 3.4) to generate a gt heatmap like original one in my experiments.

I changed the original network like this, I treat the front few blocks(between the first basic block and encoder-decoder block) as a encoder at input scale, and insert a decoder block after original encoder-decoder block. And a longer skip connection is added to connect the two blocks. In my few experiments, this network can work well despite much more computational cost.

How about this network? The following is corresponding PyTorch code:

```
    def __init__(self, input_channels, output_channels):
        super(V2VModel, self).__init__()

        self.front_layers = nn.Sequential(
            Basic3DBlock(input_channels, 16, 7),
            #Res3DBlock(16, 16)
        )

        self.skip_res0 = Res3DBlock(16, 16)  # new added skip connection at input scale

        self.encoder0 = nn.Sequential(  # treat original front few blocks as an encoder at input scale
            Pool3DBlock(2),
            Res3DBlock(16, 32),
            Res3DBlock(32, 32),
            Res3DBlock(32, 32),
        )

        self.encoder_decoder = EncoderDecorder()

        self.decoder0 = nn.Sequential(  # new added decoder at input scale
            Res3DBlock(32, 32),
            Upsample3DBlock(32, 16, 2, 2)
        )

        self.back_layers = nn.Sequential(
            Res3DBlock(16, 32),  # change (32, 32) to (16, 32) to keep channel consistency since new added decoder0
            Basic3DBlock(32, 32, 1),
            Basic3DBlock(32, 32, 1),
        )

        self.output_layer = nn.Conv3d(32, output_channels, kernel_size=1, stride=1, padding=0)

        self._initialize_weights()

    def forward(self, x):
        x = self.front_layers(x)

        skip_x0 = self.skip_res0(x)
        x = self.encoder0(x)
        x = self.encoder_decoder(x)
        x = self.decoder0(x)
        x = x + skip_x0

        x = self.back_layers(x)

        x = self.output_layer(x)
        
        return x
```
