### ISSUE TITLE
Pre-computed centers for ITOP dataset seems problematic

### ISSUE THREAD

**Issue by jakeju92** [mks0601/V2V-PoseNet_RELEASE#34]
Hi Moon,

I came across a problem while inspecting the depth map and pre-computed center from ITOP dataset. Here is the result:
![dm1](https://user-images.githubusercontent.com/5748897/50326040-0953ec80-0523-11e9-9e53-f803b1f23f84.png)
![dm2](https://user-images.githubusercontent.com/5748897/50326043-0c4edd00-0523-11e9-941c-bc6ca8c742b8.png)
![dm3](https://user-images.githubusercontent.com/5748897/50326046-0d800a00-0523-11e9-8cab-9cd5d6364c7e.png)
![dm4](https://user-images.githubusercontent.com/5748897/50326047-0eb13700-0523-11e9-8a2e-9f110e6cb2ce.png)
![dm5](https://user-images.githubusercontent.com/5748897/50326048-107afa80-0523-11e9-8e6f-dfb0e6172e32.png)
The center is denoted by a red dot. However, it seems that the red dots are not the real center of the human body. Why is that? Did I miss anything?

**Comment by mks0601** [comment]
Hi jb892,

I did not visualized the estimated centers on the ITOP dataset.
If you used front-view centers to visualize above images and correctly transformed the centers to the pixel coordinates (using my code), there would be no problem.
Note that the provided centers are estimation values, not GT values. Therefore, some errors might exist.

**Comment by jakeju92** [comment]
Thanks for your reply!

I will take a closer look at your code.  Cheers!

**Comment by jakeju92** [comment]
Just found that the camera intrinsic parameters I used: fx, fy was wrong. I took them from the website of ITOP. The correct value should be fx = fy = 241.42 .
![correct_center](https://user-images.githubusercontent.com/5748897/50470917-7668f580-09ed-11e9-9acd-2d6b5f4c1426.png)

**Comment by mks0601** [comment]
The camera parameters and pixel2world, world2pixel functions were from ITOP dataset website, and they worked well. The dataset has been changed? Can you tell me the address of the site? It seems https://www.albert.cm/projects/viewpoint_3d_pose/ is broken.

**Comment by jakeju92** [comment]
I'm not sure now since I cannot remember where did I take those wrong figures. Maybe I mistakenly took them from the NYU hand dataset. BTW, the ITOP website is down now.

**Comment by saileshprem** [comment]
The new ITOP website is here: https://www.alberthaque.com/projects/viewpoint_3d_pose/
