### ISSUE TITLE
How background removal works for train data?

### ISSUE THREAD

**Issue by jakeju92** [mks0601/V2V-PoseNet_RELEASE#36]
Hi Moon,

I'm having problem about the voxelization part. I understand how you generate the refPoint for background removal. However, my implementation result doesn't seem to be correct. 
Here is the Point cloud:
![pcd_itop](https://user-images.githubusercontent.com/5748897/51181530-5d75a500-1906-11e9-9af5-654678efbae4.png)
Resulting Voxels.
![voxel](https://user-images.githubusercontent.com/5748897/51181536-62d2ef80-1906-11e9-86cc-0baefd78f7ad.jpg)
Why the background is not removed? What is the mechanism that controls how to crop the point cloud based on the refPoint?

**Comment by mks0601** [comment]
Can you show me where is the reference point in the below figure?

**Comment by jakeju92** [comment]
![pcd2](https://user-images.githubusercontent.com/5748897/51248634-c1ae6c80-19cb-11e9-9cdd-c75425309517.png)
![pcd1](https://user-images.githubusercontent.com/5748897/51248635-c1ae6c80-19cb-11e9-817e-ae4b78937e25.png)
I cannot show it in Voxellation. I just plot the original point cloud and refpoint. The refpoint seems correct to me

**Comment by mks0601** [comment]
`generate_cubic_input` of `util.lua` creates voxel grids from point cloud.

In `discretize` of `util.lua`, point cloud coordinates are discretized by pre-defined croppedSz.
After that, `scattering` of `util.lua` scatter discretized coordinates in the voxel grids. Note that points whose coordinates is outside of voxel grids are removed by `lower_mask` and `upper_mask`.
Did you use my code?

**Comment by jakeju92** [comment]
No, I never used lua before. But I have read your code and try to understand what's going on. For Scattering part, it is really hard to understand. For example, the line you get the lower mask: `lower_mask = (coord[1]:ge(1)):cmul(coord[2]:ge(1)):cmul(coord[3]:ge(1))`. What is ge? What's going on here? Could you please explain in details what have you done in scattering part? Thanks a lot!

**Comment by mks0601** [comment]
You can find the meaning of `ge` or `le` in google easily. There is an official lua torch doc and many sites https://www.google.com/search?q=lua+torch+ge&rlz=1C1NHXL_enKR711KR711&oq=lua+torch+ge&aqs=chrome..69i57.3127j0j1&sourceid=chrome&ie=UTF-8

`ge` means greater or equal than, and `le` means less or equal than.

**Comment by jakeju92** [comment]
Cool thanks
