### ISSUE TITLE
Steps to run the ITOP dataset

### ISSUE THREAD

**Issue by zhengyuezhi** [mks0601/V2V-PoseNet_RELEASE#38]
Hello, thank you for your open program, I read your readme, still can't know the visual human body posture estimation steps to run the program, can you tell me?
How to generate result_', db, '_pixel.txt' and result_', db, '_world.txt'

In world2pixel.py
Labels = np.loadtxt('result.txt')
Labels = np.reshape(labels, (-1, jointNum, 3))
Labels[:,:,0],labels[:,:,1] = world2pixel(labels,fx,fy,imgWidth,imgHeight)
Labels = np.reshape(labels,(-1,jointNum*3))

Np.savetxt('result_pixel.txt', labels, fmt='%0.3f')
Where is the result.txt file?

**Comment by mks0601** [comment]
When you run my model in testing mode, it would save `result.txt` file. You can use this. See test.lua for more details.

**Comment by zhengyuezhi** [comment]
how to run your model in testing mode？

**Comment by mks0601** [comment]
Set `mode='test'` in `config.lua` and run `run_me.lua`. For more details, read README.

**Comment by zhengyuezhi** [comment]
thank you，If you have a question and ask you again, thank you very much.

**Comment by mks0601** [comment]
Perfect. Ask me if you meet any problem.

**Comment by bearpaw** [comment]
Thank you @mks0601 for the code! I realized that the default dataset in `config.lua` is `ICVL`. Did you use different parameters for training/testing on other datasets (e.g., MSRA or ITOP)? 

To be specific, do we have to adjust the values of `originalSz, croppedSz, poolFactor` to get the correct crops for different datasets? Thanks!

**Comment by mks0601** [comment]
Hi! You don't have to change them.
