### ISSUE TITLE
I have a problem in testing ITOP

### ISSUE THREAD

**Issue by zhengyuezhi** [mks0601/V2V-PoseNet_RELEASE#39]
HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 140034839357248:
  #000: H5F.c line 511 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1452 in H5F_open(): unable to open file: name = '/media/zhengyuezhi/ren/3D_ human_pose/V2V-PoseNet_RELEASE/data/ITOP/side_view/ITOP_side_nil_depth_map.h5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 733 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: H5FDsec2.c line 346 in H5FD_sec2_open(): unable to open file: name = '/media/zhengyuezhi/ren/3D_ human_pose/V2V-PoseNet_RELEASE/data/ITOP/side_view/ITOP_side_nil_depth_map.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
/home/zhengyuezhi/torch/install/bin/luajit: /home/zhengyuezhi/torch/install/share/lua/5.1/hdf5/file.lua:12: attempt to concatenate 'int64_t' and 'string'
stack traceback:
	/home/zhengyuezhi/torch/install/share/lua/5.1/hdf5/file.lua:12: in function '__init'
	...e/zhengyuezhi/torch/install/share/lua/5.1/torch/init.lua:91: in function <...e/zhengyuezhi/torch/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'open'
	./data/ITOP/data.lua:62: in function 'load_depthmap'
	test.lua:28: in function 'test'
	run_me.lua:79: in main chunk
	[C]: in function 'dofile'
	...ezhi/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

Why does the file /media/zhengyuezhi/ren/3D_human_pose/V2V-PoseNet_RELEASE/data/ITOP/side_view/ITOP_side_nil_depth_map.h5' appear? Shouldn't it be an ITOP_side_test_depth_map.h5 file?

**Comment by mks0601** [comment]
Did you set directory in `src/$DATASET/data.lua` properly?
