### ISSUE TITLE
mrsa_center_refined

### ISSUE THREAD

**Issue by konrad-marzec** [mks0601/V2V-PoseNet_RELEASE#41]
Whats the difference between `center_test_1_refined.txt` and `center_train_1_refined.txt` ? How `*_refined.txt` are build ? (i mean what data and in which order is used to build for example `center_train_1_refined.txt`) 

MSRA consist of 76500 frames why 
sum of lines in center_test_1_refined and center_train_1_refined = 76391

**Comment by mks0601** [comment]
You should perform cross-validation for train and test on the MSRA dataset. `center_train_1_refined.txt`  and `center_test_1_refined.txt` are used when you train your model on other subjects and test on subject 1, respectively. The author of MSRA dataset has updated the dataset and removed some invalid frames. Maybe you should download newer version of the datatset.
