### ISSUE TITLE
BatchSize setting

### ISSUE THREAD

**Issue by dragonbook** [mks0601/V2V-PoseNet_RELEASE#43]
Hi,

What's your batchSize values in those different datasets(e.g. msra, nyu) experiments? I see batchSz=1 in [config.lua](https://github.com/mks0601/V2V-PoseNet_RELEASE/blob/master/src/config.lua#L39), is that applied to all your experiments?

I trained few models on MSRA hand dataset and my own smaller dataset(not about hand) with [V2V-PoseNet-pytorch](https://github.com/dragonbook/V2V-PoseNet-pytorch), I found that the smaller batchSizes often achieve much better results. And the models perform bad if batchSize upto 32 or 64. Have you faced similar situation in your trainings(with your own torch7 implementation)?

Thanks.

**Comment by mks0601** [comment]
Sorry, that was a typo. I changed it to batchsize=8. Also, I havent't experiment for more batch size cases.

**Comment by dragonbook** [comment]
Ok, thanks!
