### ISSUE TITLE
Estimate 3D hand pose in ASL Finger Spelling Dataset

### ISSUE THREAD

**Issue by Bob130** [mks0601/V2V-PoseNet_RELEASE#44]
Can I estimate 3D hand pose (uvd) in [ASL Finger Spelling Dataset](http://empslocal.ex.ac.uk/people/staff/np331/index.php?section=FingerSpellingDataset) using the pretrained models?
Note that the resolution of the given depth images is different and there is no camera configuration.
Thanks in advance~

**Comment by mks0601** [comment]
If the camera intrinsic parameters are not available, the depth images cannot be converted to the point cloud. If you want to use orthographical perspective, then just lift the depth images and converting them to voxel representation should work.
