### ISSUE TITLE
reference point

### ISSUE THREAD

**Issue by Ericjiejie** [mks0601/V2V-PoseNet_RELEASE#48]
hi@mks0601
can you tell me how to get reference point of MSRA dataset， because i find the numble of sample with MSRA dataset downloaded on net is less than your provided.  i need to product new reference point of dataset. thanks

**Comment by Ericjiejie** [comment]
supplement : a reference points  is also a center point to preprocess the points of  hand

**Comment by mks0601** [comment]
Hi, I often got some requests that my MSRA dataset results have different number of frames. I'll update those things soon and release the code of reference point network. Meanwhile, you can just implement the network, which is not that hard.

**Comment by Ericjiejie** [comment]
Thanks for your response.  I have another question ,why the value of the first 8499 rows in center_train_1_refined.txt is different with center_test_0_refined.txt. In my opinion,i think the refpoint of same frame is same. I dont understand that. If you have time ,please tell me the reason of my question!

**Comment by mks0601** [comment]
Hi, where did you download MSRA dataset?

**Comment by Ericjiejie** [comment]
It is same with  your provided link in readme.txt, but i can't open it again now.

**Comment by Ericjiejie** [comment]
https://www.dropbox.com/s/c91xvevra867m6t/cvpr15_MSRAHandGestureDB.zip?dl=0
Maybe my network can‘t connect it

**Comment by mks0601** [comment]
I downloaded it with your link. Thank you.

**Comment by mks0601** [comment]
I checked the number of frame and it is same with my original estimations on MSRA dataset.

**Comment by Ericjiejie** [comment]
Thanks for your check.
What is the number of your frame? 76391? I checked the number of frame on MSRA dataset is 76375.

**Comment by mks0601** [comment]
I downloaded the dataset using your link and checked the number of frame is 76391. The related issue has been discussed in [here](https://github.com/xinghaochen/awesome-hand-pose-estimation/issues/2)

**Comment by Ericjiejie** [comment]
I browsed the link you provided and knew what happened. However, it's strange for me. i downloaded the dataset with the same link with your before three months ago. I didn't know why.
I would download it again.
Thank you for your recent reply three thousand times!
