### ISSUE TITLE
Why I get an image of a hand gesture standing on its head

### ISSUE THREAD

**Issue by huangshaoguang** [mks0601/V2V-PoseNet_RELEASE#49]
Why I get an image of a hand gesture standing on its head（all the results are the same!）:
![1](https://user-images.githubusercontent.com/18713992/59335896-11e9ea80-8d30-11e9-961e-2a69553ed816.jpg)

**Comment by mks0601** [comment]
Is this result from MSRA dataset?

**Comment by ZhuaMei** [comment]
Yes. I encountered the same situation.

**Comment by canuck6ix** [comment]
Naive question @mks0601 : which script generates the above image?

**Comment by ZhuaMei** [comment]
@canuck6ix V2V-PoseNet_RELEASE/vis/msra/draw_MSRA.m
