### ISSUE TITLE
The Code of PYTHON,Tensorflow or used on the  Windows

### ISSUE THREAD

**Issue by SLIiii** [mks0601/V2V-PoseNet_RELEASE#5]
Hi,Is this programe has other dependency code like python?Or is it has the version of tensorflow?I'm trying to rebuild it on the Windows but the framework maynot working well.

**Comment by mks0601** [comment]
Hi, the code is implemented under torch7 framework on the Ubuntu 16.04.
This link (https://github.com/torch/torch7/wiki/Windows) would be helpful if you want to run this code on the Window.

Also, I have plan to re-implement this project under pytorch framework, but no plan for TensorFlow.

**Comment by SLIiii** [comment]
WOW,thanks for the links, It's so helpful. And I also intrested for the code of pytorch, hope you can complete your plan at an early date.

**Comment by mks0601** [comment]
Yep, thanks for having interest in my research. Feel free to ask me if you have any problem.

**Comment by moranli19** [comment]
Is there any other version of your fully-implemented project on pytorch?
Thanks a lot!

**Comment by mks0601** [comment]
Here is 3rd party pytorch implementation repo
https://github.com/dragonbook/V2V-PoseNet-pytorch
