### ISSUE TITLE
Itop dataset pixel and world coordinate values

### ISSUE THREAD

**Issue by ML-DL-AI-SS** [mks0601/V2V-PoseNet_RELEASE#52]
Hi!
I have a question regarding the world  to pixel and pixel to world conversion in data.lua you have taken the intrinsic camera calibration parameter cx=cy=0.0035 as given in the itop dataset website and in viz/itop/world2pixel.py you have taken instrinsic camera parameter fx=fy= 285.714. why do we have two different definations for the same function? Could you please make it clear for me?

And also for camera calibration in your paper the extrinsic parameters where given as:
rotation [-40,40] 
translation [-8,8] 
Did you use the same parameters for itop dataset too?

Thank you!!

**Comment by mks0601** [comment]
Hi,

Actually, 1/285.714 = 0.0035, so it does not matter.
For the second question, I did not use camera extrinsic parameters (and I think they are not available in dataset.). The rotation and translation things are for data augmentation (rotating or translating voxels)

**Comment by ML-DL-AI-SS** [comment]
Thanks a lot for such a prompt response. I'll get back to if I have any other questions :)
