### ISSUE TITLE
Dataset issue

### ISSUE THREAD

**Issue by Fazlik995** [mks0601/V2V-PoseNet_RELEASE#53]
Hi, Gyeongsik

Thanks for sharing your awesome work.

In your paper you used depth images with 3D joint locations.
  
I wonder can i apply your method for depth images without 3D joint locations(only depth image)?

Thanks

**Comment by mks0601** [comment]
Do you mean the V2V-PoseNet can be trained in a self-supervised way?
For 3D hand shape estimation, I think so. However, for 3D hand pose estimation, I'm not sure. 
You may want to see [this paper](http://www.vision.ee.ethz.ch/~wanc/papers/cvpr2019.pdf).

**Comment by Fazlik995** [comment]
Thank you.

I have one more question

Currently, I am working on gesture recognition and my datasets are DHG-14/28 and Shrec'17. 

They both contain depth images(whole body, not only hand). However, dataset include 3D coordinates of hand.

I wanna re-extract 3D coordinates of hand using your method. But you implemented your method for  datasets which contain only hands and when you voxelize, u only voxelized hand itself.

I am not sure dataset with whole body(not only hand) is suitable for your method, bce ig i voxelize i voxelize whole body not only hand.

What do you think, is it possible to implement your method for my datasets.

Sorry if I could not explain properly my issue.

I just wanna know ur opinion.

**Comment by mks0601** [comment]
I think you should get some bounding boxes of hand and fed the region to my model?
