### ISSUE TITLE
dataset center extraction

### ISSUE THREAD

**Issue by Fazlik995** [mks0601/V2V-PoseNet_RELEASE#54]
Hi, @mks0601 

Could u give more info about extraction center location extraction using DP++.

I m using another hand gesture dataset and i need center location to train using my own dataset.

**Comment by mks0601** [comment]
I implemented exactly the same network described in Deep Prior++ paper. It is not very complicated system, so I think you can implement it.

**Comment by Fazlik995** [comment]
thank you!

One more question. Exactly which part of your code extract 3D coordinates of hand: voxelized part or V2V model?

Bce in my case I only wanna apply your code to extract 3D coordinates of hand

**Comment by mks0601** [comment]
L51 of https://github.com/mks0601/V2V-PoseNet_RELEASE/blob/master/src/test.lua
