### ISSUE TITLE
png2bin file

### ISSUE THREAD

**Issue by Fazlik995** [mks0601/V2V-PoseNet_RELEASE#55]
Did someone had a problem in png2bin file?

It shows error below:

Error using fgets
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in fgetl (line 32)
[tline,lt] = fgets(fid);

Error in handGesture (line 17)
tline = fgetl(fp);

Even though i entered filepath correctly

**Comment by mks0601** [comment]
Sorry for late reply, but I don't have any issues :( Could you check the filepath again?
