### ISSUE TITLE
Testing image of depth map

### ISSUE THREAD

**Issue by Ershebet** [mks0601/V2V-PoseNet_RELEASE#57]
Hello! How can I test with my own image of depth map?
I have some images of depth maps with hands. I want to try to plot the graphics of it, but don't understand some things. Do I need to create 3D coordinates of each image by myself?
What script will help me?

**Comment by mks0601** [comment]
You can mimic src/data/ANY_DB/data.lua

**Comment by otepencelik** [comment]
Hi @Ershebet . Did you manage to write a test code for your own depth maps? I want to try the same thing but I have no idea how to read these Lua codes and use them. Can you please share with me if you did it?
