### ISSUE TITLE
Why the functions pixel2world and world2pixel are implemented differently for different datasets?

### ISSUE THREAD

**Issue by LYKlyk** [mks0601/V2V-PoseNet_RELEASE#59]
In dataset MSRA: world2pixel(x,y,z) local pixelY = imgHeight/2 **-** fy * torch.cdiv(y,z)
In dataset ICVL: world2pixel(x,y,z) local pixelY = imgHeight/2 **+** fy * torch.cdiv(y, z)

**Comment by mks0601** [comment]
Hi, sorry for the late reply.

It is because MSRA dataset use different coordinate system.
