### ISSUE TITLE
How to get exact 3D coordinates from voxelized outputs

### ISSUE THREAD

**Issue by siyuan-peng** [mks0601/V2V-PoseNet_RELEASE#66]
The output of V2V is a voxelized heatmap cube for each keypoint, but in real applications we want to predict the exact locations of each keypoint.

How do we get 3D coordinates in world coordinate from V2V voxelized outputs? Is it just simply finding the voxel with largest confidence score, warping the voxel center to world coordinates and treating this point as the final location for this keypoint?

**Comment by mks0601** [comment]
Q. Is it just simply finding the voxel with largest confidence score, warping the voxel center to world coordinates and treating this point as the final location for this keypoint?
A. Yes

See [this](https://github.com/mks0601/V2V-PoseNet_RELEASE/blob/b91a69f3031869a192ccaf6b7339a3e4c5fb7eb7/src/util.lua#L73)

**Comment by siyuan-peng** [comment]
> Q. Is it just simply finding the voxel with largest confidence score, warping the voxel center to world coordinates and treating this point as the final location for this keypoint? A. Yes
> 
> See [this](https://github.com/mks0601/V2V-PoseNet_RELEASE/blob/b91a69f3031869a192ccaf6b7339a3e4c5fb7eb7/src/util.lua#L73)

Thank you for your quick response!!

Will this result in a loss in precision? Since now the final output world locations can only lie on voxel centers, there is an inevitable loss which depends on the voxel size.

Is there any way to improve this? I'm thinking of taking the "center of mass" of the voxelized 3D heatmaps, but I'm not sure whether this will lead to better results.

**Comment by mks0601** [comment]
We observed that the effect of the loss in precision is marginal. Instead, you can use soft-argmax.
