### ISSUE TITLE
A confused of the ITOP data about Test Code 

### ISSUE THREAD

**Issue by SLIiii** [mks0601/V2V-PoseNet_RELEASE#7]
Hi,Thanks for your help,I'm begining to run the code now.But I find some question make me confused.
1.in the line 28 of src/test.lua,the code is:

local depthimage = load_depthmap(input_name),

but in the line 59 of src/data/ITOP/data.lua,the def of depthmap is:

function load_depthmap(fileId,db_type)
local file = hdf5.open(db_dir .. 'ITOP_' .. db .. '_' .. tostring(db_type) .. '_depth_map.h5','r'),_

it has some question of work because the db_type is nil

2.I downloaded the [center_trainset] [center_testset] [models] of the ITOP Human Pose Dataset (front-view)
2.1.I find the models have ten folders,named 'epoch1~10' respectively,every folder has a 'model.net',but the test process just need one file called 'model.net',I,m can not choose the right one,so how to use it ?
2.2.In the line 93 of src/data/ITOP/data.lua,I find the code:
for line in io.lines(center_dir .. "center_" .. tostring(db_type) .. ".txt") do
		table.insert(refPt_,line)
	end
and I'm put the 'center_test.txt' in  the corresponding path and it working,is it the right way to use this data?

**Comment by mks0601** [comment]
1. oh, sorry. you have to change the test.lua code into 
 `local depthimage = load_depthmap(input_name,"test") `

2.1 You can use only one model for testing. The reason why I uploaded multiple models is epoch ensemble described in my paper.
2.2  Yes. The db_type is "test" when you load the testset. 

I`ll modify the typo in my released version code soon.

**Comment by SLIiii** [comment]
Thank you~
