### ISSUE TITLE
How to read the output of test?

### ISSUE THREAD

**Issue by SLIiii** [mks0601/V2V-PoseNet_RELEASE#8]
Hi,thanks for your help,I have rebuilt the system.But I can not understand the output the of Test on ITOP dataset.
(1,.,.) = 
  0  0  2
  0  0  2
  0  0  2
  0  0  2
  0  0  2
  0  0  2
  0  0  2
  0  0  2
  0  0  2
  0  0  2
  0  0  2
  0  0  2
  0  0  2
  0 -1  2
  0 -1  3
[torch.CudaLongTensor of size 1x15x3]
The code said this  is the 3D joint coordinates (final output) in world coordinate system, I'm confused that why the result is integer and range in [-1,3], the coordinate of x is zero only and how to show it like the figure 13 or 14 in the paper?Is I doing some wrong way that make the result stranger,or need other system to evaluate the result?

**Comment by mks0601** [comment]
The type conversion to the CudaLongTensor causes this error. I fixed and commit that.

**Comment by SLIiii** [comment]
I convert the type of output to CudaTensor,the result:
(1,.,.) = 
  0.0695  0.4745  3.0172
  0.0695  0.2927  3.0627
 -0.1123  0.2927  3.0627
  0.2058  0.2927  3.0627
 -0.3396  0.1108  2.8354
  0.3877  0.0654  2.8354
 -0.4305  0.1108  2.5172
  0.4331  0.1108  2.5172
  0.0695  0.0199  3.1081
 -0.0669 -0.2528  3.1081
  0.1604 -0.2528  3.1081
 -0.1123 -0.7528  3.0627
  0.1149 -0.7528  3.1081
 -0.1123 -1.1619  3.2445
  0.1149 -1.2073  3.2445
[torch.CudaTensor of size 1x15x3]
The error looks like been fixed.

**Comment by mks0601** [comment]
The code convert the typr of output tensor to the cudatensor, so you don't have to do that manually. All you have to do is just save the result before conversion to the original type(cudalongtensor). Anyway, good to solve problem. Close this issue.
