### ISSUE TITLE
How to use the function 'generate_heatmap_gt'

### ISSUE THREAD

**Issue by SLIiii** [mks0601/V2V-PoseNet_RELEASE#9]
Hi,It's so convenient to use your code.
I find tool function called "generate_heatmap_gt(heatmap,jointWorld,refPt,newSz,angle,trans)" in line 141,
What the( 'heatmap','refPt','newSz','angle','trans')exactly means?How to preprocess the data to generate these parameter?

I also confused about the process of DeepPrior++ in Section 4 of the paper.The original code is used to predict 3D locations of hand, how to translate it to be used on humanbody?

**Comment by SLIiii** [comment]
And is the 'invalid' in 'center_train.txt' means the corresponding frame in the training data not use is the experience? I find the input of trainsz from 39795 to 17951 after processing.So it means the DeepPrior++ work can not process these frame and give up them?

**Comment by mks0601** [comment]
1. heatmap: a tensor to contain generated 3D heatmap
refPt: referece point
newSz, angle, trans: variables for data augmentations
Actually, those are written in the comment of the code

2. The center estimator in DeepPrior++ is used. In other words, the computed hand/human centers are saved in center_train or center_test.txt

3. I will clarify what invalid frame means in the README.MD. It is not fault of the center estimator from the DeepPrior++. In the ITOP dataset, a variable which indicates each frame is valid or not is defined. That is exactly same with invalid in the center_train or center_test.txt

**Comment by SLIiii** [comment]
Thanks for your anwser and I will close this issue~
